# Generated by Django 4.2.30 on 2026-06-11 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Autor')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id_editora', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Editora')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'db_table': 'editoras',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('num_paginas', models.PositiveIntegerField(verbose_name='Número de Páginas')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa do Livro')),
                ('autores', models.ManyToManyField(related_name='livros', to='books.autor', verbose_name='Autores')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='books.editora', verbose_name='Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id_resenha', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(verbose_name='Texto da Resenha')),
                ('data_resenha', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resenha')),
                ('spoiler', models.BooleanField(default=False, verbose_name='Contém Spoiler')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to='books.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resenha',
                'verbose_name_plural': 'Resenhas',
                'db_table': 'resenhas',
                'unique_together': {('usuario', 'livro')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(verbose_name='Texto do Comentário')),
                ('data_comentario', models.DateTimeField(auto_now_add=True, verbose_name='Data do Comentário')),
                ('resenha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='books.resenha', verbose_name='Resenha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id_estante', models.AutoField(primary_key=True, serialize=False)),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('pagina_atual', models.PositiveIntegerField(default=0, verbose_name='Página Atual')),
                ('percentual_lido', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual Lido')),
                ('status', models.CharField(choices=[('lendo', 'Lendo'), ('lido', 'Lido'), ('quero ler', 'Quero Ler'), ('abandonado', 'Abandonado')], default='quero ler', max_length=20, verbose_name='Status de Leitura')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to='books.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
                'db_table': 'estantes',
                'unique_together': {('usuario', 'livro')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota (0 a 5)')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='books.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacoes',
                'unique_together': {('usuario', 'livro')},
            },
        ),
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id_amizade', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('aceita', 'Aceita'), ('recusado', 'Recusado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Amizade',
                'verbose_name_plural': 'Amizades',
                'db_table': 'amizades',
                'unique_together': {('solicitante', 'destinatario')},
            },
        ),
    ]
